apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  namespace: dev
  name: spring-petclinic-angular
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-petclinic-angular
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/beeNotice/spring-petclinic-tanzu
      ref:
        branch: main
    subPath: spring-petclinic-angular
