apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  namespace: dev
  name: spring-petclinic-vets-service
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-petclinic-vets-service
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/beeNotice/spring-petclinic-tanzu
      ref:
        branch: main
    subPath: spring-petclinic-vets-service
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17.*"
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
