spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres-tanzu-app
    username: pgappuser
    password: pgappuser
    driverClassName: org.postgresql.Driver

management:
  metrics:
    export:
      wavefront:
        enabled: false
