spring:
  application:
    name: spring-petclinic-vets
  profiles:
    active: local
  cloud:
    config:
      # Do not rely on config server
      enabled: false
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      wavefront:
        enabled: false
